<?php
/**
 * @file
 *
 * Main module file.
 */

include_once 'easyddb_dashboard_notification.api.inc';

/**
 * Implements hook_menu().
 */
function easyddb_dashboard_notification_menu() {
  $items = array();

  $items['admin/config/ding/dashboard_notification'] = array(
    'title' => 'Dashboard notification',
    'description' => 'View and customize notification settings.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('easyddb_dashboard_notification_admin_form'),
    'access arguments' => array('access dashboard notification'),
    'file' => 'easyddb_dashboard_notification.admin.inc',
  );

  return $items;
}

/**
 * Implements hook_permission().
 */
function easyddb_dashboard_notification_permission() {
  $perm = array();

  $perm['access dashboard notification'] = array(
    'title' => t('Dashboard notification'),
    'description' => t('Manage dashboard notification settings, such as names and e-mail\'s.'),
  );

  return $perm;
}

/**
 * Implements hook_theme().
 */
function easyddb_dashboard_notification_theme($existing, $type, $theme, $path) {
  $hooks = array();

  $hooks['leditor_mail'] = array(
    'variables' => array(),
    'template' => 'node-actions-leditor',
    'path' => $path . '/templates',
  );

  $hooks['editor_mail'] = array(
    'variables' => array(),
    'template' => 'node-actions-editor',
    'path' => $path . '/templates',
  );

  return $hooks;
}

/**
 * Implements hook_editorial_status_changed().
 */
function easyddb_dashboard_notification_editorial_status_changed($action, $node) {
  // @todo Make some static array or define admin form.
  $roles = array(
    EDITORIAL_ACTION_PUSH => array('editor'),
    EDITORIAL_ACTION_APPROVE => array('local editor'),
    EDITORIAL_ACTION_REJECT => array('local editor'),
  );

  if (isset($roles[$action])) {
    easyddb_dashboard_notification_user_notify($action, $node, $roles[$action]);
  }

}
